version: "3.1"

services:
  front-dev:
    image: node:18.16.0
    command: bash -c "npm install && npm run dev"
    # user: "$(id -u):$(id -g)"
    working_dir: /opt/front
    volumes:
      - ./front:/opt/front
    
    network_mode: "host"
